export const ERROR_MSG: { [key: number | string]: string } = {
  1001: 'Invalid Parameters',
  1002: "User can't login, multiple users exists",
  1003: "User doesn't exist",
  1004: "User can't login, email not found",
  1005: 'Invalid Credentials. %d attempts left',
  1006: 'DeviceId not exists',
  1007: 'Max Incorrect Login Attempt Reached',
  1008: 'Failed To Generate Token',
  1010: 'User is in dormant list',
  1011: 'failed to fetch user details',
  1012: 'Failed To Generate OTP',
  1013: 'Generate Otp Response Failed With Errorcode',
  1014: 'Incorrect password!!!',
  1015: 'Failed To Validate OTP!!',
  1016: 'Validate Otp Response Failed With Errorcode',
  1017: "Password don't match",
  1018: "New password can't be same as old password",
  1019: 'Failed To Create Password Hash',
  1020: 'Please Enter A Valid Password',
  1021: 'Password Cannot Be Same as Previous Passwords',
  1022: 'Unable to update password',
  1023: 'DeviceId Already Exists',
  1024: 'Failed To Update Device Details',
  1025: 'Failed To Validate Email',
  1026: 'Invalid Password',
  1027: 'PAN not found',
  1028: 'Invalid Username',
  1029: 'Email already exists, try using username',
  1030: 'User is locked',
  1051: 'Empty Username',
  1052: 'Empty Password',
  1053: 'Empty Username And Password',
  1054: "User can't login, mobile not found",
  1055: "User can't login, username not found",
};
