const { API_TIMEOUT, ACCESS_TOKEN_REQUEST_HEADER_KEY, API_BASE_URL, AUTH_BASE_URL } = process.env;

const TIMEOUT = (API_TIMEOUT || 3000) as number;

const ACCESS_TOKEN_RESPONSE_HEADER_KEY = 'X-Access-Token';
const SESSION_ID_REQUEST_HEADER_KEY = 'X-Session-ID';
const SESSION_ID_RESPONSE_HEADER_KEY = 'X-Session-ID';
const API_KEY_HEADER_KEY = 'X-API-Key';
const APP_UID_REQUEST_HEADER_KEY = 'X-App-UID';
const APP_UID_RESPONSE_HEADER_KEY = 'X-App-UID';

const DEFAULT_CONSTANTS = {
  ACCESS_TOKEN_REQUEST_HEADER_KEY,
  ACCESS_TOKEN_RESPONSE_HEADER_KEY,

  SESSION_ID_REQUEST_HEADER_KEY,
  SESSION_ID_RESPONSE_HEADER_KEY,

  API_KEY_HEADER_KEY,

  APP_UID_REQUEST_HEADER_KEY,
  APP_UID_RESPONSE_HEADER_KEY,

  TIMEOUT,
  BASE: API_BASE_URL,
  AUTH_BASE: AUTH_BASE_URL,
};

export default DEFAULT_CONSTANTS;
